### ISSUE TITLE
Errori file

### ISSUE THREAD

**Issue by rickycorte** [rickycorte/EmyTagBot#4]
Alcuni file sono presi come foto anche se non lo sono
`Traceback (most recent call last):
Jan 21 22:46:22 emytagbot app[web] info   File "/app/.heroku/python/lib/python3.6/site-packages/telegram/ext/dispatcher.py", line 279, in process_update
Jan 21 22:46:22 emytagbot app[web] info     handler.handle_update(update, self)
Jan 21 22:46:22 emytagbot app[web] info   File "/app/.heroku/python/lib/python3.6/site-packages/telegram/ext/commandhandler.py", line 171, in handle_update
Jan 21 22:46:22 emytagbot app[web] info     return self.callback(dispatcher.bot, update, **optional_args)
Jan 21 22:46:22 emytagbot app[web] info   File "src/main.py", line 210, in claim
Jan 21 22:46:22 emytagbot app[web] info     data = get_message_data(update.message.reply_to_message)
Jan 21 22:46:22 emytagbot app[web] info   File "src/main.py", line 168, in get_message_data
Jan 21 22:46:22 emytagbot app[web] info     return {"type":"image", "data":message.photo[0].file_id}
Jan 21 22:46:22 emytagbot app[web] info IndexError: list index out of range `

**Comment by rickycorte** [comment]
Fixed in: https://github.com/rickycorte/EmyTagBot/commit/e1a1f1e3449a49781a96ffb0fa6c19c46fb03e8d
