### ISSUE TITLE
bug comando /aset

### ISSUE THREAD

**Issue by rickycorte** [rickycorte/EmyTagBot#6]
Il comando da errori nel recuperare il contenuto da usare nel tag
` Jan 26 23:13:11 emytagbot app[web] ERROR 2018-01-26 22:13:11,976 - telegram.ext.dispatcher - ERROR - An uncaught error was raised while processing the update
Jan 26 23:13:11 emytagbot app[web] info Traceback (most recent call last):
Jan 26 23:13:11 emytagbot app[web] info   File "/app/.heroku/python/lib/python3.6/site-packages/telegram/ext/dispatcher.py", line 279, in process_update
Jan 26 23:13:11 emytagbot app[web] info     handler.handle_update(update, self)
Jan 26 23:13:11 emytagbot app[web] info   File "/app/.heroku/python/lib/python3.6/site-packages/telegram/ext/commandhandler.py", line 171, in handle_update
Jan 26 23:13:11 emytagbot app[web] info     return self.callback(dispatcher.bot, update, **optional_args)
Jan 26 23:13:11 emytagbot app[web] info   File "src/main.py", line 352, in admin_set
Jan 26 23:13:11 emytagbot app[web] info     data = get_message_data(update.reply_to_message)
Jan 26 23:13:11 emytagbot app[web] info AttributeError: 'Update' object has no attribute 'reply_to_message' `

**Comment by rickycorte** [comment]
Fixato in: https://github.com/rickycorte/EmyTagBot/commit/5ebcaf3a6d4c3184542b496b178f91d4150db87b
